services:
  postgres-test:
    image: postgres:15
    container_name: postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"


  scitech-newsservice:
    image: aliquamsiderea/scitech_newsservice:0.1.0
#    build: .
    container_name: scitech-newsservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/scitech_newsservice
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8083:8083"
    depends_on:
      - postgres-test
    restart: unless-stopped

volumes:
  postgres-data:
#  timescaledb-data:

